# 1. NODE.JS BACKEND DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopeasy-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: shopeasy-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
          - name: GEMINI_API_KEY
            value: "your_gemini_key_here"
          - name: DATABASE_URL
            value: "postgresql://postgres.cjdynhzbzmqthxkiyvpu:Reshmi&&2004@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres"
          # IMPORTANT: Tell Node where to find the Python services
          - name: FRAUD_API_URL
            value: "http://fraud-service:5001"
          - name: CHATBOT_API_URL
            value: "http://chatbot-service:6000"

---

# 2. FRAUD AI DEPLOYMENT (Python)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopeasy-fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-app
  template:
    metadata:
      labels:
        app: fraud-app
    spec:
      containers:
      - name: fraud-api
        image: shopeasy-fraud:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5001

---

# 3. CHATBOT API DEPLOYMENT (Python)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopeasy-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-app
  template:
    metadata:
      labels:
        app: chatbot-app
    spec:
      containers:
      - name: chatbot-api
        image: shopeasy-chatbot:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 6000
